# Generated by Django 6.0 on 2026-01-01 07:41

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Администратор'), ('DOCTOR', 'Врач'), ('NURSE', 'Медсестра'), ('REGISTRAR', 'Регистратор'), ('ANALYST', 'Аналитик')], default='DOCTOR', max_length=20, verbose_name='Роль')),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+79991234567'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('medical_license', models.CharField(blank=True, max_length=50, verbose_name='Медицинская лицензия')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Специализация')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Отделение')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Дата приема на работу')),
                ('is_active', models.BooleanField(default=True, help_text='Отметьте, если пользователь должен считаться активным. Уберите отметку вместо удаления учётной записи.', verbose_name='Активен')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['last_name', 'first_name'],
                'permissions': [('can_view_statistics', 'Может просматривать статистику'), ('can_export_data', 'Может экспортировать данные'), ('can_manage_users', 'Может управлять пользователями'), ('can_view_all_patients', 'Может просматривать всех пациентов'), ('can_edit_all_patients', 'Может редактировать всех пациентов')],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='Время входа')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('success', models.BooleanField(default=True, verbose_name='Успешный вход')),
                ('failure_reason', models.CharField(blank=True, max_length=200, verbose_name='Причина неудачи')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История входа',
                'verbose_name_plural': 'История входов',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/photos/', verbose_name='Фотография')),
                ('signature', models.ImageField(blank=True, help_text='Электронная подпись для документов', null=True, upload_to='users/signatures/', verbose_name='Подпись')),
                ('education', models.TextField(blank=True, verbose_name='Образование')),
                ('qualifications', models.TextField(blank=True, verbose_name='Квалификации')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Стаж работы (лет)')),
                ('theme', models.CharField(choices=[('light', 'Светлая'), ('dark', 'Темная'), ('auto', 'Авто')], default='light', max_length=20, verbose_name='Тема интерфейса')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], default='ru', max_length=10, verbose_name='Язык интерфейса')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Последний IP входа')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='Последняя активность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
