# Generated by Django 6.0 on 2026-01-01 09:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код МКБ-10')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование диагноза')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Диагноз МКБ-10',
                'verbose_name_plural': 'Диагнозы МКБ-10',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default='M', max_length=1, verbose_name='Пол')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('birth_place', models.CharField(blank=True, max_length=255, verbose_name='Место рождения')),
                ('citizenship', models.CharField(default='РФ', max_length=100, verbose_name='Гражданство')),
                ('address', models.TextField(verbose_name='Адрес постоянного места жительства')),
                ('workplace', models.CharField(blank=True, max_length=255, verbose_name='Место работы')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('profession', models.CharField(blank=True, max_length=255, verbose_name='Профессия')),
                ('marital_status', models.CharField(choices=[('S', 'Холост/Не замужем'), ('M', 'Женат/Замужем'), ('D', 'Разведен(а)'), ('W', 'Вдовец/Вдова')], default='S', max_length=2, verbose_name='Семейное положение')),
                ('education', models.CharField(choices=[('N', 'Нет образования'), ('P', 'Начальное'), ('S', 'Среднее'), ('SP', 'Среднее специальное'), ('H', 'Высшее'), ('UH', 'Неоконченное высшее')], default='S', max_length=2, verbose_name='Образование')),
                ('admission_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время поступления')),
                ('admission_from', models.CharField(blank=True, max_length=255, verbose_name='Откуда поступил')),
                ('delivered_by', models.CharField(blank=True, max_length=255, verbose_name='Кем доставлен')),
                ('referral_diagnosis', models.TextField(blank=True, verbose_name='Диагноз направившего учреждения')),
                ('admission_diagnosis', models.TextField(verbose_name='Диагноз при поступлении')),
                ('admission_mkb_code', models.CharField(blank=True, max_length=20, verbose_name='Код МКБ-10 при поступлении')),
                ('discharge_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата выписки')),
                ('discharge_diagnosis', models.TextField(blank=True, verbose_name='Диагноз при выписке')),
                ('discharge_mkb_code', models.CharField(blank=True, max_length=20, verbose_name='Код МКБ-10 при выписке')),
                ('outcome', models.CharField(blank=True, choices=[('RECOVERY', 'Выздоровление'), ('IMPROVEMENT', 'Улучшение'), ('NO_CHANGE', 'Без изменений'), ('DETERIORATION', 'Ухудшение'), ('DEATH', 'Смерть'), ('TRANSFER', 'Перевод в другую организацию')], max_length=20, verbose_name='Исход заболевания')),
                ('work_capacity', models.CharField(blank=True, choices=[('RESTORED', 'Восстановлена'), ('IMPROVED', 'Улучшена'), ('NO_CHANGE', 'Без изменений'), ('DISABLED', 'Установлена инвалидность')], max_length=20, verbose_name='Трудоспособность')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('status', models.CharField(choices=[('HOSPITALIZED', 'Госпитализирован'), ('DISCHARGED', 'Выписан'), ('TRANSFERRED', 'Переведен'), ('DIED', 'Умер')], default='HOSPITALIZED', max_length=20, verbose_name='Статус')),
                ('case_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Номер истории болезни')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Контактный телефон')),
                ('passport_series', models.CharField(blank=True, max_length=10, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(blank=True, max_length=20, verbose_name='Номер паспорта')),
                ('passport_issued_by', models.TextField(blank=True, verbose_name='Кем выдан паспорт')),
                ('passport_issue_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи паспорта')),
                ('insurance_policy', models.CharField(blank=True, max_length=50, verbose_name='Страховой полис')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('attending_physician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to=settings.AUTH_USER_MODEL, verbose_name='Лечащий врач')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patients', to=settings.AUTH_USER_MODEL, verbose_name='Кем создана запись')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
                'ordering': ['-admission_date'],
                'permissions': [('view_all_patients', 'Может просматривать всех пациентов'), ('edit_all_patients', 'Может редактировать всех пациентов'), ('export_patients', 'Может экспортировать данные пациентов'), ('view_statistics', 'Может просматривать статистику')],
            },
        ),
        migrations.CreateModel(
            name='Hospitalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField(verbose_name='Дата поступления')),
                ('discharge_date', models.DateField(blank=True, null=True, verbose_name='Дата выписки')),
                ('diagnosis', models.TextField(verbose_name='Диагноз')),
                ('mkb_code', models.CharField(blank=True, max_length=20, verbose_name='Код МКБ-10')),
                ('department', models.CharField(max_length=100, verbose_name='Отделение')),
                ('outcome', models.CharField(blank=True, max_length=50, verbose_name='Исход')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('attending_physician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Лечащий врач')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalizations', to='patients.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Госпитализация',
                'verbose_name_plural': 'Госпитализации',
                'ordering': ['-admission_date'],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['last_name', 'first_name', 'middle_name'], name='patients_pa_last_na_14514c_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['admission_date'], name='patients_pa_admissi_e25d31_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['status'], name='patients_pa_status_ca3fc5_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['case_number'], name='patients_pa_case_nu_e048ad_idx'),
        ),
    ]
