# Generated by Django

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PASSPORT', 'Паспорт'), ('POLICY', 'Полис ОМС'), ('INN_DOC', 'Свидетельство ИНН'), ('DIRECTION', 'Направление'), ('EEG', 'ЭЭГ'), ('EKG', 'ЭКГ'), ('MRI', 'МРТ/КТ'), ('LAB_RESULTS', 'Результаты анализов'), ('CONCLUSION', 'Заключение специалиста'), ('DISABILITY', 'Справка об инвалидности'), ('OTHER', 'Другое')], max_length=20, verbose_name='Тип документа')),
                ('title', models.CharField(max_length=200, verbose_name='Название документа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('file', models.FileField(upload_to='patient_documents/%Y/%m/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient', verbose_name='Пациент')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Документ пациента',
                'verbose_name_plural': 'Документы пациентов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalNoteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('template_type', models.CharField(choices=[('ADMISSION', 'Поступление'), ('DISCHARGE', 'Выписка'), ('PROGRESS', 'Дневник'), ('CONSULTATION', 'Консультация'), ('REFERRAL', 'Направление'), ('OTHER', 'Другое')], max_length=50, verbose_name='Тип шаблона')),
                ('content', models.TextField(verbose_name='Содержимое шаблона')),
                ('placeholders', models.JSONField(default=list, verbose_name='Плейсхолдеры')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Шаблон записи',
                'verbose_name_plural': 'Шаблоны записей',
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название чек-листа')),
                ('checklist_type', models.CharField(choices=[('ADMISSION', 'При поступлении'), ('DAILY', 'Ежедневный осмотр'), ('DISCHARGE', 'Перед выпиской'), ('EMERGENCY', 'Экстренная помощь'), ('OTHER', 'Другое')], max_length=50, verbose_name='Тип чек-листа')),
                ('items', models.JSONField(default=list, verbose_name='Пункты чек-листа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_checklists', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Шаблон чек-листа',
                'verbose_name_plural': 'Шаблоны чек-листов',
                'ordering': ['checklist_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PatientChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(default=list, verbose_name='Заполненные пункты')),
                ('notes', models.TextField(blank=True, verbose_name='Дополнительные заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('filled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filled_checklists', to=settings.AUTH_USER_MODEL, verbose_name='Заполнил')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='patients.patient', verbose_name='Пациент')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filled_checklists', to='patients.checklisttemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Чек-лист пациента',
                'verbose_name_plural': 'Чек-листы пациентов',
                'ordering': ['-created_at'],
            },
        ),
    ]