# Generated by Django 6.0 on 2026-01-02 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_add_documents_templates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientchecklist',
            name='template',
        ),
        migrations.RemoveField(
            model_name='medicalnotetemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='patientchecklist',
            name='filled_by',
        ),
        migrations.RemoveField(
            model_name='patientchecklist',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patientdocument',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patientdocument',
            name='uploaded_by',
        ),
        migrations.DeleteModel(
            name='ChecklistTemplate',
        ),
        migrations.DeleteModel(
            name='MedicalNoteTemplate',
        ),
        migrations.DeleteModel(
            name='PatientChecklist',
        ),
        migrations.DeleteModel(
            name='PatientDocument',
        ),
    ]
